### PR TITLE
Add support for command invoke on mention

### PR DESCRIPTION
**Pull request by kevinrockwell**
Allows users to @ the bot to invoke commands instead of needing to know
the prefix

Also might have formatted using black

### CODE REVIEW

**Comment by kevinrockwell** [comment]
I can undo the formatting if you want, forgot that my nvim auto does that 😅

**Comment by LoganHaug** [comment]
I can't get this to work on my testing bot, mentions seem to do nothing.

**Comment by LoganHaug** [comment]
Also I may have reformatted main, so this PR has merge conflicts lmao

**Review by LoganHaug — APPROVED** [review]
Ok this works now for some reason

**Pull request merged**
